### ISSUE TITLE
LiveView Native Clients: Use liveview-native-core that uses phoenix-channels-client

### ISSUE THREAD

**Issue by KronicDeth** [liveview-native/liveview-native-core-swift#6]

**Comment by AZholtkevych** [comment]
Blocked by [LiveView Native Clients: LiveView Native Core to use Phoenix.Channels client](https://github.com/liveview-native/liveview-native-core/issues/16)

**Comment by AZholtkevych** [comment]
Rejecting, duplicates https://github.com/liveview-native/liveview-client-swiftui/issues/1210
